[package]
name = "aoc_solns"
version = "0.1.0"
edition = "2021"
rust-version = "1.76"

[dependencies]
utils = { path = "../utils" }
aoc-client = "0.2.0"
chrono = "0.4.31"
clap = { version = "4.4.10", features = ["derive", "color"] }
