[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"
rust-version = "1.76"

[dependencies]
aoc-client = "0.2.0"
chrono = "0.4.31"
clap = { version = "4.4.10", features = ["derive", "color"] }
num-traits = "0.2.17"
