[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-client = "0.2.0"
chrono = "0.4.31"
num-traits = "0.2.17"
reqwest = "0.11.22"
utils-derive = { version = "0.1.0", path = "../utils-derive" }
